### ISSUE TITLE
thank you! <3 <3

### ISSUE THREAD

**Issue by paulirish** [mklabs/yarn-completions#16]
me finding my way here
![image](https://cloud.githubusercontent.com/assets/39191/25551308/9ff21098-2c37-11e7-9fd7-f76934aed549.png)

everything is great and i was so looking forward to this to help with completions for the `scripts`. (we have one and i can never remember if its `core-unit` or `unit-core`..). Now i'm good. :)

**Comment by mklabs** [comment]
Hey @paulirish Really glad this little package helped you in any way ^^ I'll eventually refactor this and update yarn to latest version. It needs a bit more attention.
