### ISSUE TITLE
/usr/bin/completions-yarn symlink is broken

### ISSUE THREAD

**Issue by vibl** [mklabs/yarn-completions#2]
After npm or yarn install of yarn-completions, /usr/bin/completions-yarn points to /usr/lib/node_modules/yarn-completions, which is not there.

It works after:
`sudo ln -fs ~/.yarn-config/global/node_modules/yarn-completions/bin/yarn-completions.js /usr/bin/completions-yarn`

**Comment by mklabs** [comment]
I'm not sure how and why you ended up in this configuration. From my tests across two machines with nvm, the symlink seemed fine.

I'll redo some tests but I'm not sure how I could tackle this bug from the point of view of this package.

**Comment by mklabs** [comment]
Is is something you experiment with other globally installed packages ? or just with yarn-completions ?

**Comment by vibl** [comment]
I don't recall having experienced this kind of problem before, no.

What path does the symlink points to on your machine?

**Comment by mklabs** [comment]
Weird stuff ... I'm a bit loss vs this issue

with npm

```
which completions-yarn                                    
/home/mk/.nvm/versions/node/v6.7.0/bin/completions-yarn
➜  ~ ll /home/mk/.nvm/versions/node/v6.7.0/bin/completions-yarn
lrwxrwxrwx 1 mk mk 60 oct.  18 11:59 /home/mk/.nvm/versions/node/v6.7.0/bin/completions-yarn -> ../lib/node_modules/yarn-completions/bin/yarn-completions.js
```

with yarn

```
which completions-yarn                                    
/home/mk/.nvm/versions/node/v6.7.0/bin/completions-yarn
➜  ~ ll /home/mk/.nvm/versions/node/v6.7.0/bin/completions-yarn
lrwxrwxrwx 1 mk mk 69 oct.  18 12:02 /home/mk/.nvm/versions/node/v6.7.0/bin/completions-yarn -> ../../../../../.yarn-cache/.global/node_modules/.bin/completions-yarn
```

**Comment by vibl** [comment]
I installed with `sudo npm install --global yarn-completions` or `sudo yarn add global yarn-completions`

Do you use `sudo` too?

**Comment by mklabs** [comment]
No I don't use sudo because of nvm, which gets installed in the home directory. That's why I prefer using nvm to manage my node versions. I'd recommend switching to it and see how it goes: https://github.com/creationix/nvm#install-script

**Comment by vibl** [comment]
Ok, we found the root of the problem!

There must be a way to make the `/usr/bin/completions-yarn` symlink points to `completions-yarn.js`, even for non nvm users.

I'm planning to look into nvm but your module would be useful to many more users if it didn't depend on it.

**Comment by mklabs** [comment]
It doesn't depend on it :) The way symlink are handled is the responsability of either npm or yarn, that's why I'm a bit loss regarding this issue.

I should check out installations without nvm but it requires reinstalling node which I can't do right now.

Do you mind sharing your OS and config ? And how you have installed node ? which versions and such. Thank you very much!

**Comment by vibl** [comment]
I'm currently switching to nvm. I'll tell you if it solves the bug.

I'm on Kubuntu Xenial
Node was installed with "deb https://deb.nodesource.com/node_6.x xenial main" and was up-to-date (I've removed it so you'll have to look into the repo to know the version).

Tell me if you need further info.

**Comment by vibl** [comment]
Pfiuuu... I had a hard time reinstalling yarn globally (but without sudo) after switching to nvm. I guess there was something wrong with my config...

I finally managed to do it and I removed and re-added yarn-completions. The /usr/bin/completions-yarn is ok now!

**Comment by mklabs** [comment]
👍 glad to hear that, I hope you'll enjoy nvm

**Comment by vibl** [comment]
I'm sure I'll be glad to use nvm some day :-)

Thanks a lot for this great tool and for your help!
