### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by mklabs** [mklabs/yarn-completions#8]
Hi @Matmo10

I thought about adding an issue here to maybe help you get yarn-completions work on your system. I hope you'll get this notification :)

Based on that comment: https://github.com/yarnpkg/yarn/issues/609#issuecomment-277765763

> I installed yarn-completions - didn't work. Realized it's actually some kind of plugin for tabtab, so I installed that. Still doesn't work. Re-sourced my bash profile. Still doesn't work. Is there really more configuration required?

How did you install yarn-completions ? You don't need to install tabtab separately, this is included in yarn-completions itself.

Normally, you just need to install yarn-completions with npm globally.

````
npm install yarn-completions -g
`````

What do you use for your shell ? Bash, zsh or fish ? If you use bash, you should see a line specific to tabtab, at the end of your `~/.bashrc`, that loads a shell specific script for your system and enable the completion mechanism for the command `yarn`.

**Comment by Matmo10** [comment]
You are too kind :)

Ok, I realized the problem is I use .bash_profile for my bash config instead of .bashrc, so I sourced .bashrc from my .bash_profile:

```
if [ -f ~/.bashrc ]; then
  . ~/.bashrc
fi
```

And now it works. Thanks, we can close this now! :)

**Comment by mklabs** [comment]
Great :)

**Comment by wavded** [comment]
@Matmo10 thanks!  I had the exact same problem with `bash_profile`.
