### ISSUE TITLE
'yarn upgrade-interactive' does not tab-complete

### ISSUE THREAD

**Issue by Ionaru** [mklabs/yarn-completions#9]
The command `yarn upgrade-interactive` does not tab-complete with this plugin.

**Comment by alexilyaev** [comment]
@mklabs The yarn dependency is outdated:  
`"yarn": "^0.15.1"`

We should bump the version.  
Ideally we'd somehow use the already installed version of the user instead.

**Comment by joeybaker** [comment]
@alexilyaev If we define `yarn` as a `peerDependency`, that would do the trick.
